[project]
name = "kontext-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.12.15",
]

[dependency-groups]
dev = [
    "ruff>=0.12.11",
]
